# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    # Healthcheck LS
    curl -I $(license.server.url)

    # Deloy Docker Virt Server
    docker run -d \
    -p 9080:9080 \
    -p 9617:9617 \
    -p 9618:9618 \
    --env ACCEPT_EULA=true \
    --name soavirt-server parasoft/soavirt-server

  displayName: 'Run Tests against localhost'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
